version = 0
commit_goodlist = []

[authorization."Neal H. Walfield <neal@walfield.org>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: F717 3B3C 7C68 5CD9 ECC4  191B 74E4 45BA 0E15 C957
Comment: Neal H. Walfield (Code Signing Key) <neal@pep.foundatio

xjMEWhaZ2xYJKwYBBAHaRw8BAQdAinglS6SRXyMb51hMk+mpM4y0Uh0vcGcTyXa+
BzHW2UDNOU5lYWwgSC4gV2FsZmllbGQgKENvZGUgU2lnbmluZyBLZXkpIDxuZWFs
QHBlcC5mb3VuZGF0aW9uPsKTBBMWCgA7AhsBCAsJCAcNDAsKBRUKCQgLAh4BAheA
FiEE9xc7PHxoXNnsxBkbdORFug4VyVcFAmOJ8pAFCQ01v7UACgkQdORFug4VyVeq
yQEApGhF3Pgb3Vo46phH/mYl17pp3ItOhV25m93OKVziawAA/iMDxo18/YQB0pHU
X2qBxI5KI2LOGklcz+xFkzTl41oKwpMEExYKADsCGwEICwkIBw0MCwoFFQoJCAsC
HgECF4AWIQT3Fzs8fGhc2ezEGRt05EW6DhXJVwUCYaeAZAUJCXIaCQAKCRB05EW6
DhXJVy9uAPwIJ4BYuCTwXPuI2+TGx/uFD70r2VnN8N3gM+VOsXVpOQD+I2XlVoH6
xjd+qKgtU1Lz6N/mmtnd5tn65NuQYefWOwHCkwQTFgoAOwIbAQgLCQgHDQwLCgUV
CgkICwIeAQIXgBYhBPcXOzx8aFzZ7MQZG3TkRboOFclXBQJfwQDZBQkHi5p+AAoJ
EHTkRboOFclXU5MA/jhbDaD66ujGn1JIYsdM/5gP6aY5XhUKAMtMAJ6HtAYCAP0U
rNha5/Bxf6IbuRixmjnNyH4zFqIjxEvq4LrzJKYsD8KTBBMWCgA7AhsBCAsJCAcN
DAsKBRUKCQgLAh4BAheAFiEE9xc7PHxoXNnsxBkbdORFug4VyVcFAl3acN0FCQWl
CoIACgkQdORFug4VyVfjEgD+JwBkErm7OYoWAOqII0kDmLOfRpdcH+80z8JYhafR
whQBANKZD+4bbA6Te53+wtUAbUX9zMBO+YficBn68CuJoIYEwpMEExYKADsWIQT3
Fzs8fGhc2ezEGRt05EW6DhXJVwUCWhaZ2wIbAQUJA8JnAAgLCQgHDQwLCgUVCgkI
CwIeAQIXgAAKCRB05EW6DhXJV1yiAP4+yNBQTzwOPm8ac6TgU0VyDDK2ERpAzq63
Vr4kPLJ/kQD+IJ2tfeSJHQafVkjlwl9Qq+iQRgpxg7ikrGx5eB+qQgrOMwRaFppu
FgkrBgEEAdpHDwEBB0CZj70mwULzrmO1aCPfIu214uWkVaoLCCpjP2nzPgtY/MLA
LwQYFgoAIBYhBPcXOzx8aFzZ7MQZG3TkRboOFclXBQJaFppuAhsCAIEJEHTkRboO
FclXdiAEGRYKAB0WIQR/r27XI4FDVXvfftJoY8mtW00i0wUCWhaabgAKCRBoY8mt
W00i07taAP9eFdQHtJ+a+kw9lSOhKY8BdizoKGjGCSDbtLgeBsYGeQEAvq2sa9Kn
UTB4udn7nS101y10tkqAt80sHgCoNRK8VA2+YgEAqvjzLAAybCHb0CpS8RC2prk/
SD4X2fxa6FA8TtAeS34BAKNewx4iekrsOKO1i0aHInI5OGvbaY/2ddovUrKHNX0K
=thbJ
-----END PGP PUBLIC KEY BLOCK-----
"""
