name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast Forwarding
        run: |
          echo Repository is ${{ github.repository }}
          echo Triggered by issue ${{ github.event.issue.number }}
          echo Triggered from ${{ github.event.issue.url }}

          echo "Trying to fast forward HEAD to $GITHUB_SHA"
          echo HEAD:
          git log -n 1 HEAD
          echo
          echo $GITHUB_SHA:
          git log -n 1 $GITHUB_SHA

          git merge --ff-only $GITHUB_SHA
          git push origin

          echo Posting comment.
          curl --silent --show-error -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.issue.url }}/comments \
            -d '{"body":"Fast-forward job"}'
