name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast Forwarding
        run: |
          echo "Fast forwarding"
          git push origin $GITHUB_SHA:$(git branch --show-current)

