name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast Forwarding
        run: |
          echo Repository is ${{ github.repository }}
          echo Triggered by issue ${{ github.event.issue.number }}
          echo Triggered from ${{ github.event.issue.url }}
          echo guthub.head_ref:  ${{ github.head_ref }}
          echo guthub.ref:  ${{ github.ref }}
          echo guthub.ref_name:  ${{ github.ref_name }}

          echo "Trying to fast forward $GITHUB_REF to ${{ github.head_ref }}"
          echo $GITHUB_REF:
          git log -n 1 $GITHUB_REF
          echo
          echo ${{ github.head_ref }}:
          git log -n 1 ${{ github.head_ref }}

          # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
          #
          # - GITHUB_SHA: Last commit on default branch.
          # - GITHUB_REF: Default branch.
          #git switch -c pr-$PR_HEAD $PR_HEAD
          #git merge --ff-only $GITHUB_SHA
          #git push origin

          echo Posting comment.
          curl --silent --show-error -- location \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.issue.url }}/comments \
            -d '{"body":"Fast-forward job"}'
