name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: ${{ github.event.issue.pull_request
            && github.event.issue.state == 'open'
            && contains(github.event.comment.body, '/fast-forward') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast Forwarding
        run: |
          # All of the event properties are held under the
          # github.event context, which is also available as
          # JSON-encoded data in the file $GITHUB_EVENT_PATH.
          #
          # For an issue_comment event:
          #
          # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
          #
          # env; echo "github.event's value:"; cat ${{ github.event_path }}

          LOG=$(mktemp)
          {
            # echo Repository is ${{ github.repository }}
            # echo Triggered by issue ${{ github.event.issue.number }}
            echo "Triggered from ${{ github.event.comment.html_url }} by ${{ github.triggering_actor }}."
            echo

            # Get the PR metadata.
            EVENT=$(mktemp)
            curl --silent --show-error --location \
              -X GET \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ github.event.issue.pull_request.url }} >$EVENT

            # This was the value of the branch at the time the PR was
            # created.
            # BASE_SHA=$(jq -r '.base.sha' <$EVENT)
            BASE_REF=$(jq -r '.base.ref' <$EVENT)

            PR_SHA=$(jq -r '.head.sha' <$EVENT)
            PR_REF=$(jq -r '.head.ref' <$EVENT)

            echo "Trying to fast forward \`$BASE_REF\`:"
            echo
            echo '```shell'
            git log --decorate=short -n 1 "origin/$BASE_REF"
            echo '```'
            echo
            echo "to \`$PR_REF\` ($PR_SHA):"
            echo
            echo '```shell'
            git log --decorate=short -n 1 "origin/$PR_REF"
            echo '```'
            echo

            if ! git merge-base --is-ancestor "origin/$BASE_REF" "origin/$PR_REF"
            then
                echo -n "Can't fast forward."
                echo -n " \`$BASE_REF\` $(git rev-parse origin/$BASE_REF)"
                echo -n " is not a direct ancestor of"
                echo -n " \`$PR_REF\` $(git rev-parse origin/$PR_REF)."

                MERGE_BASE=$(git merge-base "origin/$BASE_REF" "origin/$PR_REF" || true)
                if test x"$MERGE_BASE" = x
                then
                    echo " Branches don't appear to have a common ancestor."
                else
                    echo " Branches appear to have diverged at $MERGE_BASE:"
                    echo
                    echo '```shell'
                    git log --pretty=oneline --graph \
                      "^$MERGE_BASE^" "origin/$BASE_REF" "origin/$PR_REF"
                    git log --decorate=short -n 1 "$MERGE_BASE"
                    echo '```'
                    echo
                    echo "Rebase locally, and then force push to \`$PR_REF\`."
                fi
            else
                # https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#check-if-a-user-is-a-repository-collaborator
                COLLABORATORS_URL="${{ github.repository.collaborators_url }}"
                echo "COLLABORATORS_URL: $COLLABORATORS_URL"
                COLLABORATORS_URL="${COLLABORATORS_URL%\{/collaborator\}}/${{ github.event.sender.login }}"
                echo "COLLABORATORS_URL 2: $COLLABORATORS_URL"
                if curl --silent --show-error --location \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    --head \
                    "$COMMENTS_URL"
                    | awk '/^HTTP/ { \
                        if ($2 == "204") {
                          exit 0;
                        } else {
                          print "Access denied: "$2;
                          exit 1;
                        }
                      }'
                then
                  echo '```shell'
                  (
                    PS4='$ '
                    set -x
                    git push origin "$PR_SHA:$BASE_REF"
                  )
                  echo '```'
                else
                  echo "Please be patient. A project maintainer will"
                  echo " look at your pull request."
                fi
            fi
          } 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" "$LOG"

          # On GITHUB_STEP_SUMMARY:
          #
          # https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

          COMMENT=$(mktemp)
          jq -n --rawfile log "$LOG" '{ "body": $log }' >"$COMMENT"

          COMMENTS_URL="${{ github.event.issue.url }}/comments"
          echo "Posting comment to $COMMENTS_URL."
          curl --silent --show-error --location \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$COMMENTS_URL" \
            -d "@$COMMENT"
