name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/fast-forward') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast Forwarding
        run: |

          # All of the event properties are held under the
          # github.event context, which is also available as
          # JSON-encoded data in the file $GITHUB_EVENT_PATH.
          #
          # echo github.event's value:; cat $GITHUB_ENV
          LOG=$(mktemp)
          {
            echo Repository is ${{ github.repository }}
            echo Triggered by issue ${{ github.event.issue.number }}
            echo Triggered from ${{ github.event.issue.url }}
            echo Triggered by ${{ github.triggering_actor }}

            EVENT=$(mktemp)
            curl --silent --show-error --location \
              -X GET \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ github.event.issue.pull_request.url }} >$EVENT

            PR_SHA=$(jq -r '.head.sha' <$EVENT)
            PR_REF=$(jq -r '.head.ref <$EVENT)
            BASE_SHA=$(jq -r '.base.sha <$EVENT)
            BASE_REF=$(jq -r '.base.ref <$EVENT)

            echo "Trying to fast forward $BASE_REF ($BASE_SHA) to $PR_REF ($PR_SHA)"
            echo $BASE_REF ($BASE_SHA):
            git log -n 1 $BASE_REF
            echo
            echo $PR_REF ($PR_SHA):
            git log -n 1 $PR_PR

            git checkout $BASE_REF
            git merge --ff-only $PR_REF
            git push origin
          } | tee $LOG

          MSG=$(mktemp)
          jq -n --arg log "$(cat $LOG)" '{"body":$log}'

          echo Posting comment.
          curl --silent --show-error --location \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.issue.url }}/comments \
            -d "@$MSG"
