name: on-pr
on:
  pull_request_target:
      types: [opened, reopened, synchronize]
jobs:
  check-fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checking if fast forwarding is possible
        run: |
          # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request

          env
          echo "github.event's value:"; cat $GITHUB_ENV

          LOG=$(mktemp)
          {
            # echo Repository is ${{ github.repository }}
            # echo Triggered by issue ${{ github.event.issue.number }}
            echo Triggered from ${{ github.event.pull_request }} by @${{ github.sender }}.
            echo

            # This was the value of the branch at the time the PR was
            # created.
            # BASE_SHA=$(jq -r '.base.sha' <$EVENT)
            BASE_REF=${{ github.event.pull_request.base.ref }}

            PR_SHA=${{ github.event.pull_request.head.sha }}
            PR_REF=${{ github.event.pull_request.head.ref }}

            echo "Trying to fast forward \`$BASE_REF\`:"
            echo
            echo '```shell'
            git log --decorate=short -n 1 "origin/$BASE_REF"
            echo '```'
            echo
            echo "to \`$PR_REF\` ($PR_SHA):"
            echo
            echo '```shell'
            git log --decorate=short -n 1 "origin/$PR_REF"
            echo '```'
            echo

            if ! git merge-base --is-ancestor "origin/$BASE_REF" "origin/$PR_REF"
            then
                echo -n "Can't fast forward."
                echo -n " \`$BASE_REF\` $(git rev-parse origin/$BASE_REF) is not a direct ancestor"
                echo -n " of \`$PR_REF\` $(git rev-parse origin/$PR_REF). "
                MERGE_BASE=$(git merge-base "origin/$BASE_REF" "origin/$PR_REF" || true)
                if test x"$MERGE_BASE" = x
                then
                    echo "Branches don't appear to have a common ancestor."
                else
                    echo "Branches appear to have diverged at $MERGE_BASE:"
                    echo '```shell'
                    git log --pretty=oneline --graph "^$MERGE_BASE^" "origin/$BASE_REF" "origin/$PR_REF"
                    git log --decorate=short -n 1 "$MERGE_BASE"
                    echo '```'
                fi
            else
                echo "Add a comment with \`/fast-forward\` to fast forward \`$BASE_REF\` to \`PR_REF\`."
            fi
          } 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" "$LOG"

          # On GITHUB_STEP_SUMMARY:
          #
          # https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

          MSG=$(mktemp)
          jq -n --arg log "$(cat $LOG)" '{ "body": $log }' >"$MSG"

          echo Posting comment.
          cat ${{ github.event_path }}
          curl --silent --show-error --location \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.comments_url }}/comments \
            -d "@$MSG"
